### ISSUE TITLE
Serveur FTP

### ISSUE THREAD

**Issue by Elyes1981** [Elyes1981/Social_Service#10]
Dans la version actuelle de la solution, on stocke une photo d'identité, un document d'identité, .. . Il faudra prévoir aussi un serveur FTP. Toujours penser à une solution open source pour moindre coup

**Comment by FirasMessaoudi** [comment]
J'ai modifié l'architecture de la solution en proposant l'integration du google drive comme  solution (j'ai ajouté aussi qq liens utiles pour aider à integrer google drive avec spring boot)
